Adding docs around the Subnet Available collector and analyzer
replicatedhq/troubleshoot.sh pull request #473
Opened 2023-02-17 04:56 UTC by CpuID

Self explanatory.

Should be merged with a release of https://github.com/replicatedhq/troubleshoot/pull/1004 (with the version number it was introduced?)

2023-02-17 17:28 UTC, paigecalvert commented
Holding on the docs review until Evans has a chance to review, but wanted to ask if this new topic might also need to be manually added to the TOC? Asking because I did not see it in the TOC in the Netlify preview (I think it's supposed to be in this section): https://deploy-preview-473--troubleshoot-sh.netlify.app/docs/host-collect-analyze/overview/

2023-02-17 19:32 UTC, banjoh approved these changes
Content LGTM. We'll want to wait for the feature to be released first before merging though

2023-02-17 21:47 UTC, jonquil2002 commented
@CpuID Looks good! I just made some minor edits to your content to reflect our style guide.

Two things I think are missing:

- It looks like it should be listed and linked to from the All Host Collectors page. https://deploy-preview-473--troubleshoot-sh.netlify.app/docs/host-collect-analyze/all/
- It seems to be missing from the TOC on the left. It should be added alphabetically, though there is at least one mistake in that TOC.

Lmk when you're ready for a final review.

2023-02-20 13:46 UTC, banjoh commented on docs/source/host-collect-analyze/subnetAvailable.md
> +    - subnetAvailable:
Please update this example in light of [this comment](https://github.com/replicatedhq/troubleshoot/pull/1004#pullrequestreview-1305738327)

2023-02-20 13:46 UTC, banjoh commented on docs/source/host-collect-analyze/subnetAvailable.md
> +    - subnetAvailable:
Please update this example in light of [this comment](https://github.com/replicatedhq/troubleshoot/pull/1004#pullrequestreview-1305738327)

2023-02-20 13:46 UTC, banjoh requested changes

2023-02-20 13:46 UTC, banjoh commented on docs/source/host-collect-analyze/subnetAvailable.md
> +      outcomes:
Please update this example in light of [this comment](https://github.com/replicatedhq/troubleshoot/pull/1004#pullrequestreview-1305738327)

2023-02-22 04:27 UTC, CpuID commented
> I just made some minor edits to your content to reflect our style guide.

thanks @jonquil2002 :)

2023-02-22 05:21 UTC, CpuID commented
I'll sort out getting this on the TOC, I missed that one 👍

2023-02-22 10:20 UTC, banjoh approved these changes

2023-03-06 15:04 UTC, jonquil2002 commented
@CpuID @banjoh lmk when you're ready for a final docs review! :)

2023-03-07 02:58 UTC, CpuID commented
Sorted out the TOC + a few other outstanding items mentioned above, thanks @jonquil2002 @paigecalvert 

This is ready to merge once https://github.com/replicatedhq/troubleshoot/pull/1004 is released 👍

2023-03-07 16:00 UTC, jonquil2002 approved these changes
lgtm

2023-03-08 11:54 UTC, banjoh approved these changes
All good!

2023-03-10 04:35 UTC, CpuID commented
heads up: https://github.com/replicatedhq/troubleshoot/pull/1004 is merged but not released yet

holding on a merge of this PR until it's released

2023-03-10 05:02 UTC, CpuID commented
Released, 0.59.0

2023-03-10 05:03 UTC, merged