New doc for Event analyzer
replicatedhq/troubleshoot.sh pull request #548
Opened 2024-03-07 03:18 UTC by nvanthao

New doc for https://github.com/replicatedhq/troubleshoot/pull/1474

2024-03-07 13:02 UTC, banjoh requested changes

2024-03-07 13:02 UTC, banjoh commented on docs/source/analyze/event.md
> +The analyzer also has access to all fields in the Event [object](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#event-v1-core), Go templating can be used for dynamic message. E.
```suggestion
The analyzer also has access to all fields in the Event [object](https://kubernetes.io/docs/reference/kubernetes-api/cluster-resources/event-v1/), Go templating can be used for dynamic message. E.g. `{{ .Reason }} {{ .InvovledObject.Name }}`
```

2024-03-07 15:46 UTC, paigecalvert approved these changes
looks good! just noticed a couple typos and I also suggested changing instances of `E.g.` to `For example`

2024-03-07 15:46 UTC, paigecalvert commented on docs/source/analyze/event.md
> +The `Event` analyzer checks if an Event is existed within the cluster resources in a given namespace.
```suggestion
The `Event` analyzer checks if an Event exists within the cluster resources in a given namespace.
```

2024-03-07 15:46 UTC, paigecalvert commented on docs/source/analyze/event.md
> +The analyzer also has access to all fields in the Event [object](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#event-v1-core), Go templating can be used for dynamic message. E.
```suggestion
The analyzer also has access to all fields in the Event [object](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#event-v1-core). Go templating can be used for dynamic message. For example, `{{ .Reason }} {{ .InvovledObject.Name }}`
```

2024-03-07 15:46 UTC, paigecalvert commented on docs/source/analyze/event.md
> +**reason**: (Required) Event Reason. E.g. `InvalidDiskCapacity`. Possible reasons list can be referred from Kubernetes [source code](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/e
```suggestion
**reason**: (Required) Event Reason. For example, `InvalidDiskCapacity`. Possible reasons list can be referred from Kubernetes [source code](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/events/event.go)
```

2024-03-07 15:46 UTC, paigecalvert commented on docs/source/analyze/event.md
> +**kind**: (Optional) The REST resource the Event represents. E.g. `Pod`
```suggestion
**kind**: (Optional) The REST resource the Event represents. For example,`Pod`
```

2024-03-08 05:16 UTC, nvanthao commented on docs/source/analyze/event.md
> +The `clusterResources` collector is automatically added and will always be present.
I copied the text from `deploymentStatus` and believe the analysis currently looks the same for others analyzers such as `statefulsetStatus`, `replicasetStatus`, `jobStatus` etc. I reckon we can discuss this in other PR to include `ignoreIfNoFiles` to more analyzers. Please let me know your thought.

2024-03-08 10:47 UTC, banjoh approved these changes

2024-03-08 11:27 UTC, merged

2024-03-08 14:02 UTC, banjoh commented on docs/source/analyze/event.md
> +The `clusterResources` collector is automatically added and will always be present.
Thinking about it some more, I think its fine to leave it as is. Anyone defining this analyser expects cluster resources to exist