feat: [sc-112277] Host DNS collector
replicatedhq/troubleshoot.sh pull request #580
Opened 2024-09-17 20:48 UTC by nvanthao

Fixes: https://app.shortcut.com/replicated/story/112277/analyse-search-domains-with-wildcard-dns-records-on-hosts

2024-09-20 14:04 UTC, xavpaice requested changes
couple of comments here

2024-09-20 14:04 UTC, xavpaice commented on docs/source/host-collect-analyze/dns.md
> +        hostnames:
let's add a collectorName here too, so we have the option to have an explanatory analyzer example too

2024-09-20 14:04 UTC, xavpaice commented on docs/source/host-collect-analyze/dns.md
> +options ndots:5
let's leave the ndots out of this example so we don't confuse folks :)

2024-09-20 14:04 UTC, xavpaice commented on docs/source/host-collect-analyze/dns.md
> +
the output will need to be two outputs with different paths if we have split the example above

2024-09-20 18:56 UTC, xavpaice reviewed
one question, otherwise lgtm.

If the `collectorName` is the same as the shared property and it's OK to skip it (even though it's not great), we can just remove that from the doc.

2024-09-20 18:56 UTC, xavpaice commented on docs/source/host-collect-analyze/dns.md
> +##### `collectorName` (Required)
this is optional, isn't it?  It's a common parameter that is optional, but best to use.  What happens if we don't supply it, we just get the output in /host-collectors/dns/result.json?

2024-09-20 21:36 UTC, xavpaice commented on docs/source/host-collect-analyze/dns.md
> +##### `collectorName` (Required)
we've talked, this is good

2024-09-20 21:36 UTC, xavpaice submitted a review, later dismissed

2024-09-23 16:34 UTC, paigecalvert approved these changes
looks good!

2024-09-23 19:21 UTC, merged